"""
Derive K=2 first-overtone (n=1) plateau statistics from existing
Method-4 two-mode JSON files without re-running any fit.

Each JSON written by ``scripts/extract_qnm.py --two-mode`` already
contains the per-window arrays ``omegas1, taus1`` and the
``plateau_idx`` selected for the fundamental. We average the
overtone over the same plateau windows -- the Giesler, Isi, Scheel
& Teukolsky (2019) convention -- and rescale by the BH mass M to
dimensionless (M*omega_1, tau_1/M).

Writes a LaTeX table fragment to paper/tables/m4_overtones.tex and a
summary JSON to outputs/qnm/m4_overtones_summary.json.

Usage:
    python -m scripts.extract_m4_overtones
"""
from __future__ import annotations

import json
import os
import sys
from typing import Dict, List, Optional, Tuple

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

# Leaver continued-fraction values, Schwarzschild ell=2.
# n=0: Berti, Cardoso, Starinets 2009 review (CQG 26, 163001).
# n=1: Berti & Cardoso 2007 tabulation; matches qnm package (Stein 2019).
THEORY = {
    "n0": {"Mw": 0.373672, "tauOverM": 11.2407},
    "n1": {"Mw": 0.346711, "tauOverM": 3.65114},
}


def _load(path: str) -> Optional[dict]:
    if not os.path.isfile(path):
        return None
    with open(path) as fh:
        return json.load(fh)


def _plateau_overtone(d: dict) -> Tuple[float, float, float, float, int]:
    """Return (omega1_mean, omega1_std, tau1_mean, tau1_std, n_plateau)
    averaged over the same plateau indices the fundamental used."""
    idx = d.get("plateau_idx") or []
    omegas1 = np.asarray(d.get("omegas1", []), dtype=float)
    taus1 = np.asarray(d.get("taus1", []), dtype=float)
    if not idx or omegas1.size == 0:
        return (np.nan, np.nan, np.nan, np.nan, 0)
    o = omegas1[idx]
    t = taus1[idx]
    om = o[np.isfinite(o)]
    tm = t[np.isfinite(t)]
    return (
        float(np.mean(om)) if om.size else np.nan,
        float(np.std(om)) if om.size else np.nan,
        float(np.mean(tm)) if tm.size else np.nan,
        float(np.std(tm)) if tm.size else np.nan,
        len(idx),
    )


def _pct(val: float, ref: float) -> float:
    if not (np.isfinite(val) and np.isfinite(ref) and ref != 0.0):
        return float("nan")
    return 100.0 * abs(val - ref) / abs(ref)


# Headline runs to feature. (Label, json path, M, source-tag-for-display).
# M=1 for the PINN runs (config default); FNO test BHs use the M encoded
# in their directory name.
RUNS: List[Dict] = [
    {
        "label": r"Forward PINN",
        "path": "outputs/qnm/zerilli_l2_greedy_f03_lbfgs30k/pinn_method4_two_mode.json",
        "M": 1.0,
    },
    {
        "label": r"Inverse PINN (variant D)",
        "path": "outputs/qnm/zerilli_l2_inverse_qnm_combo/pinn_method4_two_mode.json",
        "M": 1.0,
    },
    {
        "label": r"Curriculum PINN (3-window)",
        "path": "outputs/qnm/zerilli_l2_curriculum_3w/pinn_method4_two_mode.json",
        "M": 1.0,
    },
    {
        "label": r"FD reference ($M{=}1.009$)",
        "path": "outputs/qnm/fno_zerilli_l2_v2_GT_001_M1.009/fd_method4_two_mode.json",
        "M": 1.009,
    },
    {
        "label": r"FNO prediction ($M{=}1.009$)",
        "path": "outputs/qnm/fno_zerilli_l2_v2_pred_001_M1.009/fd_method4_two_mode.json",
        "M": 1.009,
    },
]


def main() -> int:
    rows = []
    for run in RUNS:
        d = _load(os.path.join(ROOT, run["path"]))
        if d is None:
            print(f"[warn] missing: {run['path']}", file=sys.stderr)
            continue
        M = float(run["M"])
        o1m, o1s, t1m, t1s, n_pl = _plateau_overtone(d)
        Mw1 = M * o1m
        Mw1_std = M * o1s
        tauOverM1 = t1m / M
        tauOverM1_std = t1s / M
        rows.append({
            "label": run["label"],
            "path": run["path"],
            "M": M,
            "n_plateau": n_pl,
            "Mw1": Mw1,
            "Mw1_std": Mw1_std,
            "tauOverM1": tauOverM1,
            "tauOverM1_std": tauOverM1_std,
            "Mw1_pct": _pct(Mw1, THEORY["n1"]["Mw"]),
            "tauOverM1_pct": _pct(tauOverM1, THEORY["n1"]["tauOverM"]),
            "t0_plateau_min": d.get("t0_plateau_min"),
            "t0_plateau_max": d.get("t0_plateau_max"),
        })

    # ---- summary JSON ----
    out_json = os.path.join(ROOT, "outputs", "qnm", "m4_overtones_summary.json")
    os.makedirs(os.path.dirname(out_json), exist_ok=True)
    with open(out_json, "w") as fh:
        json.dump({"theory": THEORY, "runs": rows}, fh, indent=2)
    print(f"wrote {out_json}")

    # ---- LaTeX table fragment ----
    tex_path = os.path.join(ROOT, "paper", "tables", "m4_overtones.tex")
    os.makedirs(os.path.dirname(tex_path), exist_ok=True)
    lines = []
    lines.append(r"% Auto-generated by scripts/extract_m4_overtones.py -- do not edit by hand.")
    lines.append(r"\begin{tabular}{@{}lcccc@{}}")
    lines.append(r"\toprule")
    lines.append(
        r"Source & $M\omega_1$ & $\omega_1$ err & $\tau_1/M$ & $\tau_1$ err \\"
    )
    lines.append(r"\midrule")
    th = THEORY["n1"]
    lines.append(
        rf"Leaver (theory, $n{{=}}1$) & ${th['Mw']:.4f}$ & --- & ${th['tauOverM']:.3f}$ & --- \\"
    )
    for r in rows:
        Mw1 = r["Mw1"]; Mw1_std = r["Mw1_std"]
        ta = r["tauOverM1"]; tas = r["tauOverM1_std"]
        Mw1_pct = r["Mw1_pct"]; ta_pct = r["tauOverM1_pct"]
        if not np.isfinite(Mw1):
            lines.append(rf"{r['label']} & --- & --- & --- & --- \\")
            continue
        lines.append(
            rf"{r['label']} & "
            rf"${Mw1:.4f}{{\pm}}{Mw1_std:.4f}$ & "
            rf"${Mw1_pct:.2f}\%$ & "
            rf"${ta:.3f}{{\pm}}{tas:.3f}$ & "
            rf"${ta_pct:.1f}\%$ \\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    with open(tex_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {tex_path}")

    # ---- console preview ----
    print("\n" + "=" * 78)
    print(f"  M4 K=2 overtone plateau report (Leaver n=1: Mw={THEORY['n1']['Mw']:.4f}, "
          f"tau/M={THEORY['n1']['tauOverM']:.3f})")
    print("=" * 78)
    fmt = "  {:<34} {:>16} {:>10} {:>14} {:>10}"
    print(fmt.format("Source", "Mw_1", "err", "tau_1/M", "err"))
    for r in rows:
        if not np.isfinite(r["Mw1"]):
            print(fmt.format(r["label"], "nan", "---", "nan", "---"))
            continue
        print(fmt.format(
            r["label"],
            f"{r['Mw1']:.4f}+/-{r['Mw1_std']:.4f}",
            f"{r['Mw1_pct']:.2f}%",
            f"{r['tauOverM1']:.3f}+/-{r['tauOverM1_std']:.3f}",
            f"{r['tauOverM1_pct']:.1f}%",
        ))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
